name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app (standalone)
        run: npm run build

      - name: Prepare standalone folder for deployment
        run: |
          mkdir -p deploy
          cp -r .next/standalone deploy/
          cp -r .next/static deploy/
          cp package.json deploy/
          cp package-lock.json deploy/

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: deploy
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      # 2. Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3BDB2FE1BFD44033952F0C3E8BADA434 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1B598B495CD849E38A2AC0C6F8E51CD9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_395966662A5A485CBF6E04EA62CEF28B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'full-stack-fastapi-mongodb-app'
          slot-name: 'Production'
          package: standalone
  






