name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build Next.js app
      - name: Build Next.js app
        run: npm run build

      # 5. Prepare production package
      # Ensure node_modules + .next + public are included
      - name: Prepare production package
        run: |
          npm install --only=production

      # 6. Upload artifact for deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: |
            .
            !node_modules/.cache

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Download build artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      # 2. Login to Azure
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # 3. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'full-stack-fastapi-mongodb-app'
          slot-name: 'Production'
          package: .
  
